
services:
  mysql:
    image: mysql:8.0
    container_name: marketplace-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - marketplace-db-data:/var/lib/mysql

volumes:
  marketplace-db-data:
